mutation addQuestion($token: String!, $data: QuestionInput!) {
	admin(token: $token) {
		addQuestion(data: $data) {
			_id
			question
			author {
				firstName
				lastName
			}
			category {
				name
			}
			concept {
				_id
				name
			}
			topic {
				_id
				name
			}
		}
	}
}
