query getQuestion($token: String!, $_id: String!) {
	admin(token: $token) {
		question(_id: $_id) {
			_id
			question
			choices {
				label
				name
				answer
			}
			explanation
			concept {
				_id
				name
			}
			category {
				_id
				name
			}
			topic {
				_id
				name
			}
		}
	}
}
