query searchRecalls($token: String!, $search: String, $author: String, $category: [String], $topic: [String]) {
	admin(token: $token) {
		recalls(search: $search, author: $author, category: $category, topic: $topic) {
			_id
			question
			author {
				firstName
				lastName
			}
			category {
				name
			}
			concept {
				_id
				name
			}
			topic {
				_id
				name
			}
		}
	}
}
