query getUsers($token:String!, $search:String, $accessLevel:String){
    admin(token:$token){
        users(search:$search, accessLevel:$accessLevel){
            _id
            username
            firstName
            lastName
            # classYear
            # graduationYear
            # university
            createdAt
            lastActivity
            accessLevel
        }
    }
}
