query profile($token:String!, $_id:String!){
    restricted(token:$token){
        user(_id:$_id){
            username
            firstName
            lastName
            # classYear
            # graduationYear
            # university
            createdAt
            lastActivity
            accessLevel
        }
    }
}