mutation resetPasswordPrep($token:String!, $username:String!, $key:String!, $password:String!){
    restricted(token:$token){
        resetPassword(username:$username, key:$key, password:$password)
    }
}
