let UKMedicalSchools = [
	`Aberdeen (University of), School of Medicine`,
	`Barts and The London School of Medicine and Dentistry, Queen Mary, University of London`,
	`Birmingham (University of), School of Medicine`,
	`Brighton and Sussex Medical School`,
	`Bristol (University of), Faculty of Medicine`,
	`Cambridge (University of), School of Clinical Medicine`,
	`Cardiff University, School of Medicine`,
	`Dundee (University of), Faculty of Medicine, Dentistry and Nursing`,
	`Edinburgh (The University of), College of Medicine and Veterinary Medicine`,
	`Exeter (University of), Medical School`,
	`Glasgow (University of), College of Medical, Veterinary and Life Sciences`,
	`Hull York Medical School`,
	`Imperial College School of Medicine, London`,
	`Keele University, School of Medicine`,
	`King's College London School of Medicine (at Guy's, King's College and St Thomas' Hospital)`,
	`Lancaster University, Faculty of Health & Medicine`,
	`Leeds (University of), School of Medicine`,
	`Leicester (University of), Leicester Medical School`,
	`Liverpool (University of), Faculty of Health and Life Sciences`,
	`London School of Hygiene and Tropical Medicine (Postgraduate Medical School)`,
	`Manchester (University of), Faculty of Medical and Human Sciences`,
	`Newcastle University Medical School`,
	`Norwich Medical School, University of East Anglia`,
	`Nottingham (The University of), Faculty of Medicine and Health Sciences`,
	`Oxford (University of), Medical Sciences Division`,
	`Plymouth University Peninsula Schools of Medicine and Dentistry`,
	`Queen's University Belfast, Faculty of Medicine and Health Sciences`,
	`Sheffield (The University of), School of Medicine`,
	`Southampton (University of), School of Medicine`,
	`St Andrews (University of), Faculty of Medical Sciences`,
	`St George's, University of London`,
	`Swansea University, School of Medicine`,
	`University College London, University College Medical School`,
	`Warwick (The University of), Warwick Medical School`
];
export default UKMedicalSchools;
