#import './appointmentFragment.gql'
mutation addAppointment($token:String!, $patientId:String!, $appointment:AppointmentInput!) {
	restricted(token:$token) {
		addAppointment(patientId:$patientId, appointment:$appointment){
			_id
			firstName
			lastName
			gender
			patientNumber
			NHSnumber
			graphData {
				key
				values {
					x
					y
				}
			}
			...AppointmentInfo
		}
	}
}
