#import "./appointmentFragment.gql"

mutation deleteAppointment($token:String!, $appointmentId:String!) {
	restricted(token:$token) {
		deleteAppointment(appointmentId:$appointmentId){
			...AppointmentInfo
		}
	}
}
