#import './patientFragment.gql'
query getPatients($token: String!, $search: String) {
	restricted(token: $token) {
		patients(search: $search) {
			...PatientInfo
			appointments {
				_id
			}
		}
	}
}
