#import './patientFragment.gql'
#import './appointmentFragment.gql'
query getPatientById($token:String!, $_id:String!) {
	restricted(token:$token) {
		patient(_id:$_id){
			...PatientInfo
			graphData {
				key
				values {
					x
					y
				}
			}
			...AppointmentInfo
		}
	}
}
