mutation updateAppointment($token:String!, $appointment:AppointmentInput!) {
	restricted(token:$token) {
		updateAppointment(appointment:$appointment){
			_id
			firstName
			lastName
			gender
			patientNumber
			NHSnumber
			dateOfBirth
			createdAt
			lastUpdated
			appointments {
				_id
				clinicDate
				weight
				alsfrs {
					speech
					salivation
					swallowing
					handwriting
					cutting
					dressing
					turning
					walking
					climbing
					dyspnea
					orthopnea
					respiratory
					total
				}
				ess {
					sittingAndReading
					watching
					sittingInactive
					carPassenger
					lyingDown
					sittingAndTalking
					sittingAfterLunch
					carTraffic
					total
				}
				fvc {
					sitting
					supine
				}
				snp
				spO2
				abg {
					pH
					pO2
					pCO2
					HCO3
					be
				}
			}
		}
	}
}
