#import './appointmentFragment.gql'
mutation updateAppointment($token:String!, $appointment:AppointmentInput!) {
	restricted(token:$token) {
		updateAppointment(appointment:$appointment){
			_id
			firstName
			lastName
			gender
			patientNumber
			NHSnumber
			graphData {
				key
				values {
					x
					y
				}
			}
			...AppointmentInfo
		}
	}
}
