#import "./appointmentFragment.gql"

mutation updateAppointment($token:String!, $appointment:AppointmentInput!) {
	restricted(token:$token) {
		updateAppointment(appointment:$appointment){
			...AppointmentInfo
		}
	}
}
