mutation buildTest($token: String!, $questions: [String!]!, $topics:[String!]!, $categories: [String!]!) {
  restricted(token: $token) {
    buildTest(questions:$questions, topics:$topics, categories: $categories) {
      _id
      createdBy {
        _id
      }
      timeTaken
      correct
      percentage
      topics {
        name
      }
      categories {
        name
      }
      marks {
        question
      }
      questions {
        _id
        question
        explanation
        choices {
          name
          label
          answer
          votes
        }
		category {
		  name
		}
      }
    }
  }
}
