query getMarksheets($token:String!, $_id:String){
  restricted(token:$token){
    marksheets(author:$_id) {
      _id
      createdAt
      lastActivity
      timeTaken
      correct
      percentage
      topics{
        name
      }
      categories{
        name
      }
	  marks{
        correct
      }
      questions{
        _id
      }
    }
  }
}
