query getMarksheetById($token: String!, $_id: String!) {
	restricted(token: $token) {
		marksheet(_id: $_id) {
			_id
			createdBy {
				_id
			}
			timeTaken
			correct
			percentage
			topics {
				name
			}
			categories {
				name
			}
			marks {
	          question
	          correct
	          label
	          timeTaken
	        }
			questions {
				_id
				question
				explanation
				choices {
					name
					label
					answer
					votes
				}
				category {
					name
				}
			}
		}
	}
}
