query getUser($token: String!) {
	restricted(token: $token) {
		user {
			_id
			username
			firstName
			lastName
			classYear
			graduationYear
			university
			examDate
			createdAt
			lastActivity
			accessLevel
			progressReport {
				topic {
					_id
					name
				}
				answered
				correct
				# standardDeviation
			}
		}
	}
}
